CREATE DATABASE Mock;
CREATE TABLE User (
  USERNAME VARCHAR (50)  NOT NULL,
  PASSWORD_HASH VARCHAR (50) NOT NULL,
  PRIMARY KEY (USERNAME)
  );
CREATE TABLE USER_DETAILS (
    USER_ID INT (20) NOT NULL,
    USERNAME VARCHAR (50) ,
    FIRST_NAME CHAR (50) NOT NULL,
    LAST_NAME CHAR (50) NOT NULL,
    PHONE_NUMBER INT (10) NOT NULL,
    ADDRESS VARCHAR (50) NOT NULL,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (USERNAME) REFERENCES User(USERNAME)
);
CREATE TABLE TICKETS (
    TICKET_ID VARCHAR (50) NOT NULL,
    USER_ID INT (20),
    CLIENT_NAME CHAR (50) NOT NULL,
    PAYMENT_AMOUNT FLOAT (15,2) NOT NULL,
    PAYMENT_TYPE CHAR (50) NOT NULL,
    DATE_OF _PAYMENT DATE NOT NULL,
    DESCRIPTION VARCHAR (100),
    ATTACHMENT BLOB ,
    PRIMARY KEY (TICKET_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS (USER_ID)
);